server:
  port: 8080
# 数据库信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #一定要加serverTimezone，否则可能链接不上数据库
    url: jdbc:mysql://localhost:3306/ddd_explore?useUnicode=true&characterEncoding=utf8&useSSL=false&&serverTimezone=UTC
    username: root
    password: 123456
